Wrote code for BuildandDrawTree in main.
Haven't done much anything with the transforms or anything
I just want to commit the code, because right now, at this point,
I've lost track of my train of thought.

It does *not* compile.  But it will.

Here's the compiler output:
admin@mako:~/Documents/Thesis/OronymCode $ make treeGUI
g++ -lsqlite3  -pedantic -framework GLUT -framework OpenGL  -g -o treeGUI wordBreakdown.cpp wordBreakdown.h ../LTreeLighting/main.cpp ../LTreeLighting/Metrics.cpp ../LTreeLighting/Metrics.h
In file included from wordBreakdown.cpp:1:
wordBreakdown.h:23: error: ‘string’ does not name a type
wordBreakdown.h:24: error: ‘string’ does not name a type
wordBreakdown.cpp: In function ‘std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > discoverOronymsForPhrase(std::string)’:
wordBreakdown.cpp:227: error: ‘deadEndDelim1’ was not declared in this scope
wordBreakdown.cpp:228: error: ‘deadEndDelim2’ was not declared in this scope
wordBreakdown.cpp: In function ‘std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > findOrthoStrsForPhoneSeq(std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)’:
wordBreakdown.cpp:381: error: ‘deadEndDelim1’ was not declared in this scope
wordBreakdown.cpp:396: error: ‘deadEndDelim2’ was not declared in this scope
wordBreakdown.cpp: In function ‘void connectToPhoneticDictionaryDatabase(std::string)’:
wordBreakdown.cpp:875: warning: deprecated conversion from string constant to ‘char*’
wordBreakdown.h:23: error: ‘string’ does not name a type
wordBreakdown.h:24: error: ‘string’ does not name a type
In file included from /usr/include/c++/4.2.1/backward/vector.h:59,
                 from ../LTreeLighting/Metrics.h:13,
                                  from ../LTreeLighting/main.cpp:31:
                                  /usr/include/c++/4.2.1/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header. Please consider using one of the 32 headers found in section 17.4.1.2 of the C++ standard. Examples include substituting the <X> header for the <X.h> header for C++ includes, or <iostream> instead of the deprecated header <iostream.h>. To disable this warning use -Wno-deprecated.
                                  In file included from ../LTreeLighting/main.cpp:32:
                                  ../LTreeLighting/../OronymCode/wordBreakdown.h:23: error: ‘string’ does not name a type
                                  ../LTreeLighting/../OronymCode/wordBreakdown.h:24: error: ‘string’ does not name a type
                                  ../LTreeLighting/main.cpp: In function ‘void drawBranch(double, double, double, double, double)’:
                                  ../LTreeLighting/main.cpp:216: error: expected `;' before ‘}’ token
                                  ../LTreeLighting/main.cpp: In function ‘void drawBranchesAtFork(std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, double)’:
                                  ../LTreeLighting/main.cpp:306: error: ‘curFirstWordIter’ was not declared in this scope
                                  ../LTreeLighting/main.cpp:321: error: ‘deadEndDelim1’ was not declared in this scope
                                  ../LTreeLighting/main.cpp:321: error: ‘deadEndDelim2’ was not declared in this scope
                                  ../LTreeLighting/main.cpp:323: error: ‘drawCube’ was not declared in this scope
                                  ../LTreeLighting/main.cpp:331: error: ‘line’ was not declared in this scope
                                  ../LTreeLighting/main.cpp:336: error: conversion from ‘std::set<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >’ to non-scalar type ‘std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >’ requested
                                  ../LTreeLighting/main.cpp: In function ‘void buildAndDrawFullTree(std::string)’:
                                  ../LTreeLighting/main.cpp:281: error: too few arguments to function ‘void drawBranchesAtFork(std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, double)’
                                  ../LTreeLighting/main.cpp:351: error: at this point in file
                                  In file included from /usr/include/c++/4.2.1/backward/vector.h:59,
                                                   from ../LTreeLighting/Metrics.h:13,
                                                                    from ../LTreeLighting/Metrics.cpp:9:
                                                                    /usr/include/c++/4.2.1/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header. Please consider using one of the 32 headers found in section 17.4.1.2 of the C++ standard. Examples include substituting the <X> header for the <X.h> header for C++ includes, or <iostream> instead of the deprecated header <iostream.h>. To disable this warning use -Wno-deprecated.
                                                                    In file included from /usr/include/c++/4.2.1/backward/vector.h:59,
                                                                                     from ../LTreeLighting/Metrics.h:13:
                                                                                     /usr/include/c++/4.2.1/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header. Please consider using one of the 32 headers found in section 17.4.1.2 of the C++ standard. Examples include substituting the <X> header for the <X.h> header for C++ includes, or <iostream> instead of the deprecated header <iostream.h>. To disable this warning use -Wno-deprecated.
                                                                                     make: *** [treeGUI] Error 1
                                                                                     admin@mako:~/Documents/Thesis/OronymCode $